### PR TITLE
Avoid DeprecationWarning of collections.abc if possible

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Why not the other way around, right?

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
@fleighton do you know why the tests are not running?

**Comment by MiquelRForgeFlow** [comment]
@Nerfix

**Comment by MiquelRForgeFlow** [comment]
Anyone?

**Comment by MiquelRForgeFlow** [comment]
Please, who should I ping here to get a review? :S

**Comment by fleighton** [comment]
Hi @MiquelRForgeFlow, apologies for the delayed response. I'm looking into this now

**Review by Rurquhart — APPROVED** [review]

**Pull request merged**
